/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEBACKGROUND
#define ROOEBACKGROUND

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TMath.h"
 
class RooEBackground : public RooAbsPdf {
public:
  RooEBackground() {} ; 
  RooEBackground(const char *name, const char *title,
	      RooAbsReal& _ebx,
	      RooAbsReal& _ebslope,
	      RooAbsReal& _ebshape);
  RooEBackground(const RooEBackground& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooEBackground(*this,newname); }
  inline virtual ~RooEBackground() { }

protected:

  RooRealProxy ebx ;
  RooRealProxy ebslope ;
  RooRealProxy ebshape ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooEBackground,1) // Your description goes here...
};
 
#endif
