/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMUBACKGROUND
#define ROOMUBACKGROUND

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TMath.h"

class RooMuBackground : public RooAbsPdf {
public:
  RooMuBackground() {} ; 
  RooMuBackground(const char *name, const char *title,
	      RooAbsReal& _mubx,
	      RooAbsReal& _mubslope);
  RooMuBackground(const RooMuBackground& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMuBackground(*this,newname); }
  inline virtual ~RooMuBackground() { }

protected:

  RooRealProxy mubx ;
  RooRealProxy mubslope ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMuBackground,1) // Your description goes here...
};
 
#endif
