 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 

 #include "RooMuBackground.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 
 
 ClassImp(RooMuBackground) 

 RooMuBackground::RooMuBackground(const char *name, const char *title, 
                        RooAbsReal& _mubx,
                        RooAbsReal& _mubslope) :
   RooAbsPdf(name,title), 
   mubx("mubx","mubx",this,_mubx),
   mubslope("mubslope","mubslope",this,_mubslope)
 { 
 } 


 RooMuBackground::RooMuBackground(const RooMuBackground& other, const char* name) :  
   RooAbsPdf(other,name), 
   mubx("mubx",this,other.mubx),
   mubslope("mubslope",this,other.mubslope)
 { 
 } 



 Double_t RooMuBackground::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return exp(mubslope*TMath::Power(mubx, 0.3)) ;
 } 



